version: '3.6'

services:
  peatio:
    image: rubykube/peatio:2.0.0.alpha
    depends_on:
      - proxy
      - db
      - redis
      - rabbitmq
    env_file:
      - ../config/peatio.env
    expose:
      - "8000"
    volumes:
      - ../config/peatio/seed:/opt/peatio/config/seed
      - ../config/peatio/management_api_v1.yml:/opt/peatio/config/management_api_v1.yml
      - ../config/peatio/plugins.yml:/opt/peatio/config/plugins.yml
    labels: {}
      # traefik.enable: true
      #      traefik.frontend.rule: 'Host: peatio.wb.local'
      # traefik.port: 8000
    command: bash -c "bin/link_config && bundle exec puma --config config/puma.rb"

  barong:
    image: quay.io/openware/barong2
    env_file:
      - ../config/barong.env
    ports:
      - "8001:8001"
    volumes:
      - ../config/keys:/secrets:ro
