version: '3.6'

services:
  frontend:
    image: node:11
    volumes:
      - ../vendor/frontend:/home/node
    command:
      - sh
      - -c
      - |
        cd /home/node
        node scripts/server.js
    labels:
      traefik.enable: true
      traefik.frontend.priority: 20
      traefik.frontend.rule: "Host: www.${APP_DOMAIN}"
      traefik.port: 3000

  tower:
    image: node:11
    volumes:
      - ../vendor/tower:/home/node
    command:
      - sh
      - -c
      - |
        cd /home/node
        yarn start
    labels:
      traefik.enable: true
      traefik.frontend.priority: 40
      traefik.frontend.rule: 'Host: tower.${APP_DOMAIN}'
      traefik.port: 3000
